# Generated by Django 4.2.11 on 2024-05-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('gif_file', models.FileField(upload_to='generated_gifs/')),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
